SportsPro/Models/Incident.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;

namespace SportsPro.Models
{
    public class Incident
    {
        public int IncidentID { get; set; }


        [ForeignKey("Customer")] // name of the navigation property
        [Required]
        public int CustomerID { get; set; }     // foreign key property
        [ValidateNever]
        public Customer? Customer { get; set; }  // navigation property


        [ForeignKey("Product")] // name of the navigation property
        [Required(ErrorMessage = "Product is required")]
        public int ProductID { get; set; }     // foreign key property
        [ValidateNever]
        public Product? Product { get; set; }   // navigation property


        [ForeignKey("Technician")] // name of the navigation property
        public string? TechnicianID { get; set; } // foreign key property
        public SportsProUser? Technician { get; set; }   // navigation property



        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; } = string.Empty;

        [Required]
        public string Description { get; set; } = string.Empty;

        public DateTime DateOpened { get; set; } = DateTime.Now;

        public DateTime? DateClosed { get; set; }
    }
}

SportsPro/Models/ViewModels/IncidentViewModel.cs
using SportsPro.Models;

namespace SportsPro.Models.ViewModels
{
    public class IncidentViewModel
    {
        public IEnumerable<Technician>? Technicians{ get; set; }

        
        public List<Incident>? Incidents { get; set; }
        public List<Product>? Products { get; set; }
        public List<Customer>? Customers { get; set; }

        public Technician? Technician { get; set; }

        public Incident? Incident { get; set; }
    }
}

SportsPro/Controllers/IncidentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SportsPro.DataAccess.Interfaces;
using SportsPro.Models;
using SportsPro.Models.ViewModels;
using SportsPro.Utility;
using X.PagedList;

namespace SportsPro.Controllers
{
	[Authorize]
    public class IncidentController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly UserManager<IdentityUser> _userManager;

		public IncidentController(IUnitOfWork ctx, UserManager<IdentityUser> userManager)
		{
			_userManager = userManager;
			_unitOfWork = ctx;
		}

		

		public async Task IncidentsListInfo()
		{
			
			//store products in a viewbag,ordered by name
			ViewBag.Products =  _unitOfWork.Products.GetAll().OrderBy(prod => prod.Name).ToList();

			//get all users for tech list
			var users = _unitOfWork.SportsProUsers.GetAll().OrderBy(user => user.FirstName).ToList();

			//for each user in users get each role
			foreach (var user in users)
			{
				var roles = await _userManager.GetRolesAsync(user);
				user.Role = roles.FirstOrDefault();
				//do not include hashed password
				user.PasswordHash = null;
			}
			//store techs in a viewbag, ordered by name
			ViewBag.Technicians = users.Where(user => user.Role == RoleConstants.Role_Technician).ToList();

			//store customers in a viewbag order by name														
			ViewBag.Customers = _unitOfWork.Customers.GetAll().OrderBy(cust => cust.FirstName).ToList();
		}


		[Authorize(Roles = RoleConstants.Role_Admin)]
		//incident list
		[HttpGet]
		public async Task<IActionResult> List(string search, int? page, bool? unassigned, bool? open)
		{
			try
			{
                //set the pageSize
                var pageSize = 5;
                var pageNumber = page ?? 1; // default the pageNumber to 1 if there is no pagenumber passed in


                //get all incident
                //include Customer,Product, SportsProUser, and DateOpened
                var incidents = _unitOfWork.Incidents.GetAll(includeProperties: "Customer,Product,Technician");


                if (!string.IsNullOrEmpty(search))
                {
                    incidents = incidents.Where(incident => incident.Title.ToLower().Contains(search.ToLower()) ||  // search for the title
                                                            incident.Description.ToLower().Contains(search.ToLower()) || //search for the description
                                                            incident.Product.Name.ToLower().Contains(search.ToLower()) || //search for the product name
                                                            incident.Customer.FirstName.ToLower().Contains(search.ToLower()) || //search for the customer firstname
                                                            incident.Customer.LastName.ToLower().Contains(search.ToLower())); // search for the customer lastname
                }

                // check if unassigned filter is clicked/active for incidents
                if (unassigned == true)
                {
                    incidents = incidents.Where(incident => incident.TechnicianID == null);
                }

                //check if open incidents is clicked/active
                if (open == true)
                {
                    incidents = incidents.Where(incident => incident.DateClosed == null);
                }

                //paginates the items using X.PagedList package
                var pagedIncidents = await incidents.ToPagedListAsync(pageNumber, pageSize);

                ViewBag.search = search;

                return View("List", pagedIncidents);
            }
			catch(Exception ex) 
			{
				TempData["errorMessage"] = $"Error occurred: {ex.Message}";
                return RedirectToAction("Index", "Home");
			}
		}

        [Authorize(Roles = RoleConstants.Role_Admin)]
        // update incident list 
        //technician select list
        [Route("update-incident/select-tech/")]
		[HttpGet]
        public async Task<IActionResult> TechniciansSelectList()
        {
			try 
			{
				//get all tech
				await IncidentsListInfo();

                // returns the technicians
                return View("TechniciansSelectList");
            }
			catch (Exception ex)
			{
				TempData["errorMessage"] = $"Error occurred: {ex.Message}";
				return RedirectToAction("Index", "Home");
			}
        }



		// list of the incidents that is associeted with the selected technician
		[Route("/update-incident/list/id/{id?}")]
		[HttpGet]
        public async Task<IActionResult> UpdateIncidentsList(string technicianID, int? page)
        {
			try
			{
                //set the pageSize
                var pageSize = 5;
                var pageNumber = page ?? 1; // default the pageNumber to 1 if there is no pagenumber passed in
                                            


                List<Incident> incidents = _unitOfWork.Incidents.GetAll(includeProperties: "Customer,Technician,Product")
                                            .Where(incident => incident.TechnicianID == technicianID)
                                                   .ToList();

				SportsProUser technician = _unitOfWork.SportsProUsers.Find(tech => tech.Id == technicianID) ;
				ViewBag.Technician = technician.FullName;

				if (incidents.Count() == 0)
				{
					TempData["errorMessage"] = $"Technician {technician.FullName} Has No Open Incidents.";
					await IncidentsListInfo();
					return View("TechniciansSelectList");
				}

				var pagedIncidents = incidents.ToPagedList(pageNumber, pageSize);

                return View("UpdateIncidentsList", pagedIncidents);
            }
			catch(Exception ex)
			{
				TempData["errorMessage"] = $"Error occurred: {ex.Message}";
				return RedirectToAction("Index", "Home");
			}
        }

		
        [Route("update-incident/update/id/{id?}")]
        [HttpGet]
        public IActionResult UpdateIncident(int incidentID, string technicianID)
        {
			
            ViewBag.Action = "Update Incident";
            var incident = _unitOfWork.Incidents
                            .Find(inci => inci.IncidentID == incidentID, includeProperties: "Technician,Customer,Product");

			//check if the selected incident is in the db
			if (incident == null) 
			{
				//send error message if no incident found.
				TempData["errorMessage"] = "Incident to update not found.";
				return RedirectToAction("UpdateIncidentsList", new { technicianID = technicianID});
			}

            return View("UpdateIncident", incident);
            
        }

		
		[HttpPost]
		public IActionResult Save(Incident incident)
		{
			if (ModelState.IsValid)
			{

				//check if incident has id to update
				if (incident.IncidentID != 0)
				{
					try
					{
						//to be fixed
						var existingIncident = _unitOfWork.Incidents
											.Find(incident => incident.IncidentID == incident.IncidentID, includeProperties: "Product,Technician,Customer");

						//double check if incident exist in db
						if (existingIncident == null)
						{
							TempData["errorMessage"] = "Unable to find incident to update.";
							return View("UpdateIncident", incident);
						}
						//else if the incident exists, update the incident
						else
						{
                            existingIncident.ProductID = incident.ProductID;
                            existingIncident.CustomerID = incident.CustomerID;
                            existingIncident.DateClosed = incident.DateClosed;
                            existingIncident.DateOpened = incident.DateOpened;
                            existingIncident.Title = incident.Title;
                            existingIncident.Description = incident.Description;
                            existingIncident.TechnicianID = incident.TechnicianID;
                            TempData["successMessage"] = "Incident updated successfully.";
						}
						//save the data
						_unitOfWork.Save();

						//if the user who edit this incident is tech, return to home
						//if an admin edits this incident, return to techlist
						if (User.IsInRole(RoleConstants.Role_Admin))
						{
							return RedirectToAction("UpdateIncidentsList", new { technicianID = existingIncident.TechnicianID });
						}
						else 
						{
							return RedirectToAction("Index", "Home");
						}
					}
					catch (Exception ex)
					{
						TempData["errorMessage"] = $"Error occurred: {ex.Message}";
						return View("UpdateIncident", incident);
					}
				}
                //else if the incident has no id/ id == 0, return to select tech
                else
                {
					TempData["errorMessage"] = "Incident has no Id.";
					return View("UpdateIncident", incident);
				}
			}
			else
			{
               
                var existingIncident = _unitOfWork.Incidents
                                    .Find(incident => incident.IncidentID == incident.IncidentID, includeProperties: "Technician,Product,Customer");

                TempData["errorMessage"] = "Please input the required fields.";
                return View("UpdateIncident", existingIncident);
			}
		}


        [Authorize(Roles = RoleConstants.Role_Admin)]
        [Route("/incident/add/")]
        [HttpGet]
		public async Task<IActionResult> Add()
		{
			ViewBag.Action = "Add";

			await IncidentsListInfo();

            return View("AddEdit", new Incident());
		}

        [Authorize(Roles = RoleConstants.Role_Admin)]
        [Route("/incidents/edit/id/{id?}")]
		[HttpGet]
		public async Task<IActionResult> Edit(int id)
		{
			try 
			{
                ViewBag.Action = "Edit";

               await IncidentsListInfo();

                //find and get the incident from the db 
                var incident = _unitOfWork.Incidents.Find(incident => incident.IncidentID == id);


                return View("AddEdit", incident);
            }
			catch (Exception ex) 
			{
				TempData["errorMessage"] = $"Error occurred: {ex.Message}";

SportsPro/Views/Incident/AddEdit.cshtml
@model Incident

@{
    ViewBag.Title = ViewBag.Action + " Incident";
}



<div class="container">
    <h1>@ViewBag.Title</h1>
    <form method="post" asp-controller="Incident" asp-action="AddEdit" class="my-4">
        <div class="row mb-3">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="CustomerID">Customer:</label>
                    <select asp-for="CustomerID" class="form-control select2"
                            asp-items="@(new SelectList(
                                ViewBag.Customers, "CustomerID", "FullName", Model.CustomerID.ToString() ))">
                        <option value="">Select A Customer...</option>
                    </select>
                    <span class="text-danger" asp-validation-for="CustomerID"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="ProductID">Product:</label>
                    <select asp-for="ProductID" class="form-control select2"
                            asp-items="@(new SelectList(
                                ViewBag.Products, "ProductID", "Name", Model.ProductID.ToString() ))">
                        <option value="">Select A Product...</option>
                    </select>
                    <span class="text-danger" asp-validation-for="ProductID"></span>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input class="form-control" asp-for="Title" />
                    <span class="text-danger" asp-validation-for="Title"></span>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Description">Description</label>
                    <textarea class="form-control" asp-for="Description" rows="4"></textarea>
                    <span class="text-danger" asp-validation-for="Description"></span>
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="DateOpened">Data Opened</label>
                    <input class="form-control" asp-for="DateOpened" />
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="DateClosed">Date Closed</label>
                    <input class="form-control" asp-for="DateClosed" />
                </div>
            </div>
        </div>

        <div class="row mb-3">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="TechnicianID">Technician</label>
                    <select asp-for="TechnicianID" class="form-control select2"
                            asp-items="@(new SelectList(ViewBag.Technicians,
                                                        "Id", "FullName", Model.TechnicianID))">
                        <option value="">Assign A Technician...</option>
                    </select>
                </div>
            </div>
        </div>

        <input type="hidden" asp-for="IncidentID" />

        <div class="row mb-3">
            <div class="col-md-12">
                <button class="btn btn-primary" type="submit">Save</button>
                <a class="btn btn-primary" asp-controller="Incident" asp-action="List">Cancel</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.select2').select2();
        });
    </script>
}

SportsPro/Views/Incident/List.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@model X.PagedList.IPagedList<Incident>
@{
    ViewBag.Title = "Incident Manager";
     
    string selectedNAV(string selected)
    {
        string currentAction = ViewContext.RouteData.Values["action"].ToString();
        return (selected == currentAction) ? "active" : "";
    }
}

<h1>@ViewBag.Title</h1>

<div class="mb-4 d-flex justify-content-between">
    <a class="btn btn-outline-primary" asp-controller="Incident" asp-action="Add">Add Incident</a>

    <form method="get" asp-action="List" asp-controller="Incident" class="w-50">
        <div class="input-group">
            <input type="text" class="form-control me-1" name="search" value="@ViewBag.search" placeholder="Search...">
            <button class="btn btn-outline-primary" type="submit">Search</button>
        </div>
    </form>
</div>

<ul class="nav nav-pills mb-2">
    <li class="nav-item">
        <a class="btn btn-outline-primary  @(HttpContextAccessor.HttpContext.Request.Query.Count == 0 ? "active" : "")" 
            asp-action="List" 
            asp-controller="Incident">
            All Incidents
        </a>
    </li>

    <li class="nav-item mx-2">
        <a class="btn btn-outline-primary @(HttpContextAccessor.HttpContext.Request.Query["unassigned"] == "true" ? "active" : "")" 
            asp-action="List" 
            asp-controller="Incident" 
            asp-route-unassigned="true">
            Unassigned Incidents
        </a>
    </li>

    <li class="nav-item">
        <a class="btn btn-outline-primary  @(HttpContextAccessor.HttpContext.Request.Query["open"] == "true" ? "active" : "")" 
            asp-action="List" 
            asp-controller="Incident" 
            asp-route-open="true">
            Open Incidents
        </a>
    </li>
</ul>

@if (Model.Count > 0)
{
    @foreach (Incident i in Model)
    {
        <div class="card shadow mb-3">
            <div class="card-body">
                <h5 class="card-title">@i.Title</h5>
                <p class="card-text">Customer: @i.Customer?.FullName</p>
                <p class="card-text">Product: @i.Product?.Name</p>
                <p class="card-text">Date Opened: @i.DateOpened</p>
                @* show the date closed if it was closed *@
                @if (i.DateClosed != null)
                {
                    <p class="card-text">Date Closed: @i.DateClosed</p>
                }
                @* show the technician if it was assigned *@
                @if (i.TechnicianID != null)
                {
                    <p class="card-text">Technician: @i.Technician.FullName</p>
                }
                else
                {
                    <p class="card-text">Technician: Unassigned</p>
                }
                <div class="d-flex justify-content-end">
                    <a href="@Url.Action("Edit", "Incident", new { id = i.IncidentID })" class="btn btn-primary mx-1">Edit</a>
                    <form method="post" asp-action="Delete" asp-controller="Incident" id="deleteIncident_@i.IncidentID" onsubmit="deleteIncident(event, @i.IncidentID)">
                        <input hidden asp-for="@i.IncidentID" name="incidentID" value="@i.IncidentID"/>
                        <button class="btn btn-outline-danger" type="submit">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    }
}
else
{
    <h4 class="my-4 text-center">No Incidents...</h4>    
}

@* only show the pagination when there is more than 1 page *@
@if (Model.PageCount > 1)
{
    <div class="">
        <nav aria-label="Page navigation" class="d-flex justify-content-center">
            <ul class="pagination">
                @for (var i = 1; i <= Model.PageCount; i++)
                {
                    <li class="page-item @(Model.PageNumber == i ? "active" : "")">
                        <a class="page-link" href="@Url.Action("List", "Incident", new {page = i, search = ViewBag.search})">@i</a>
                    </li>
                }
            </ul>
        </nav>
    </div>    
}

@section Scripts{
    <script>
        function deleteIncident(event, incidentID) { 
            event.preventDefault();

            Swal.fire({
                title: "Are you sure you want to delete this incident?",
                icon:'question',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Yes, delete it'
            }).then(result => {
                if (result.isConfirmed) {
                    // submit the form
                    document.getElementById('deleteIncident_' + incidentID).submit();
                }
            });
        }
    </script>
}

SportsPro/Views/Incident/TechniciansSelectList.cshtml
@using SportsPro.Models.ViewModels

@model Technician
@{
     ViewData["title"] = "Get Technician";
}

<h1>Technician</h1>

<form name="UpdateIncidentForm" class="needs-validation"  asp-controller="Incident" asp-action="UpdateIncidentsList" method="get" novalidate>
    <div class="form-group w-50">
        <select class="form-control select2" asp-for="TechnicianID" asp-items="@(new SelectList(ViewBag.Technicians , "Id", "FullName"))" required>
            <option value="">Select Technician...</option>
        </select>
        <span class="invalid-feedback" asp-validation-for="@Model.TechnicianID"> Please Select A Technician</span>
    </div>

    <div class="mt-3">
        <button class="btn btn-primary"  type="submit" >Select</button>
        <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Cancel</a>
    </div>
</form>


@section Scripts {
    <script>
        (() => {
            'use strict'

            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            const forms = document.querySelectorAll('.needs-validation')

            // Loop over them and prevent submission
            Array.from(forms).forEach(form => {
                form.addEventListener('submit', event => {
                    if (!form.checkValidity()) {
                        event.preventDefault()
                        event.stopPropagation()
                    }

                    form.classList.add('was-validated')
                }, false);

                //make the jquery select2 function/work
                $(document).ready(function () {
                    $('.select2').select2();
                });
            });
        })();
    </script>
}

SportsPro/Views/Incident/UpdateIncident.cshtml
@model Incident
@{
    ViewData["title"] = "Edit Incident";
}




<h3 class="mt-2">@ViewBag.Action</h3>
<h5 class="mt-2">Technician Name: @Model.Technician.FullName</h5>
    
    <div class="form-group my-2">
    <label class="form-label" >Customer Name: </label>
    <input type="text" readonly="true" class="form-control" 
            value="@Model.Customer?.FullName" />
</div>

    <div class="form-group my-2">
    <label class="form-label">Product Name: </label>
    <input type="text" readonly="true" class="form-control"
            value="@Model.Product.Name" />
</div>

    <div class="form-group my-2">
    <label class="form-label" >Title: </label>
    <input type="text" readonly="true" class="form-control" asp-for="Title"  value="@Model.Title" />
</div>

    <div class="form-group my-2">
    <label class="form-label" >Date Open: </label>
    <input type="text" readonly="true" class="form-control" 
            asp-for="DateOpened"  value="@Model.DateOpened" />
</div>


<form asp-action="Save" asp-controller="Incident" method="post">
    <input type="hidden" asp-for="TechnicianID" value="@Model.TechnicianID" />
    <input type="hidden" asp-for="CustomerID" value="@Model.CustomerID"/>
    <input type="hidden" asp-for="ProductID" value="@Model.ProductID" />
    <input type="hidden" asp-for="Title" value="@Model.Title.ToString()" />
    <input type="hidden" asp-for="DateOpened" value="@Model.DateOpened" />
    <div class="row mb-3">
        <div class="col-md-12">
            <div class="form-group">
                <label asp-for="Description">Description</label>
                <textarea class="form-control" asp-for="Description" rows="4"></textarea>
                <span class="text-danger" asp-validation-for="Description"></span>
            </div>
        </div>
    </div>
    
    <div class="form-group mt-3 my-2">
        <label class="form-label" asp-for="DateClosed">Date Closed: </label>
        <input class="form-control" asp-for="DateClosed" />
    </div>


    <input type="hidden" asp-for="IncidentID"/>
    <div class="form-group mt-3 my-2">
        <button class="btn-primary btn" type="submit">Save</button>

        @* href="@Url.Action("UpdateIncidentsList", "Incident", new { technicianID = Model.TechnicianID })" *@
        @if (User.IsInRole(RoleConstants.Role_Admin))
        {
            <a class="mx-1 btn btn-primary" asp-controller="Incident"
               asp-action="UpdateIncidentsList"
               asp-route-technicianID="@Model.TechnicianID">
                Cancel
            </a>
        }
        else
        {
            <a class="mx-1 btn btn-primary" asp-controller="Home"
               asp-action="Index"
               asp-route-technicianID="@Model.TechnicianID">
                Cancel
            </a>
        }
    </div>
    
</form>

SportsPro/Views/Incident/UpdateIncidentsList.cshtml
@using SportsPro.Models.ViewModels
@model X.PagedList.IPagedList<Incident>
@* @model IncidentViewModel *@

@{
    ViewData["title"] = "Incidents List";
}

<h3 class="mt-2">Assigned Incidents </h3>

<h5 class="mt-2">Technician: @ViewBag.Technician</h5>

@if (Model.Count() > 0)
{
    @foreach (Incident i in Model)
    {
        <div class="card shadow mb-3">
            <div class="card-body">
                <h5 class="card-title">@i.Title</h5>
                <p class="card-text">Customer: @i.Customer?.FullName</p>
                <p class="card-text">Product: @i.Product?.Name</p>
                <p class="card-text">Date Opened: @i.DateOpened</p>
                @* show the date closed if it was closed *@
                @if (i.DateClosed != null)
                {
                    <p class="card-text">Date Closed: @i.DateClosed</p>
                }


                <div class="d-flex justify-content-end">
                    @* href="@Url.Action("UpdateIncident", "Incident", new { incidentID = i.IncidentID, technicianID = i.TechnicianID })" *@
                    <a asp-action="UpdateIncident" asp-controller="Incident" asp-route-incidentID="@i.IncidentID" asp-route-technicianID="@i.TechnicianID"
                        class="btn btn-primary mx-1">
                        Edit
                    </a>
                   
                    <form method="post" asp-action="Delete" asp-controller="Incident" id="deleteIncident_@i.IncidentID" onsubmit="deleteIncident(event, @i.IncidentID)">
                        <input hidden asp-for="@i.IncidentID" name="incidentID" value="@i.IncidentID" />
                        <button class="btn btn-outline-danger" type="submit">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    }
}
else
{
    <h4 class="my-4 text-center">No Incidents...</h4>
}

@* only show the pagination when there is more than 1 page *@
@if (Model.PageCount > 1)
{
    <div class="">
        <nav aria-label="Page navigation" class="d-flex justify-content-center">
            <ul class="pagination">
                @for (var i = 1; i <= Model.PageCount; i++)
                {
                    <li class="page-item @(Model.PageNumber == i ? "active" : "")">
                        <a class="page-link" href="@Url.Action("List", "Incident", new {page = i, search = ViewBag.search})">@i</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
}

<div>
    <a class="btn btn-primary" asp-controller="Incident" asp-action="TechniciansSelectList">
        Switch Technician
    </a>
</div>


@section Scripts {
    <script>
        function deleteIncident(event, incidentID) {
            event.preventDefault();

            Swal.fire({
                title: "Are you sure you want to delete this incident?",
                icon: 'question',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Yes, delete it'
            }).then(result => {
                if (result.isConfirmed) {
                    // submit the form
                    document.getElementById('deleteIncident_' + incidentID).submit();
                }
            });
        }
    </script>
}